#define new_vf_packet newvfpacket
#define ext_xn_over_d extxnoverd
#define image_x_res imagexres
#define image_y_res imageyres
#define pop_packet_state poppacketstate
#define push_packet_state pushpacketstate
#define image_width imagewidth
#define image_height imageheight
#define epdf_orig_x epdforigx
#define epdf_orig_y epdforigy
#define check_image_b checkimageb 
#define check_image_c checkimagec 
#define check_image_i checkimagei 
#define packet_byte packetbyte
#define print_creation_date printcreationdate
#define write_zip writezip
#define read_config_file readconfigfile
#define do_pdf_font dopdffont
#define get_resname_prefix getresnameprefix
#define tfm_of_fm tfmoffm
#define start_packet startpacket
#define is_cfg_truedimen iscfgtruedimen
#define write_stream_length  writestreamlength
#define update_image_procset updateimageprocset 
#define set_job_id setjobid 
#define is_pdf_image ispdfimage
#define image_pages imagepages
#define delete_image deleteimage
#define write_image writeimage
#define read_image readimage
#define check_ex_tfm checkextfm
#define set_char_map setcharmap
#define cfg_par cfgpar 
#define get_pk_char_width getpkcharwidth

#define pdf_begin_dict        zpdfbegindict
#define pdf_begin_obj         zpdfbeginobj
#define pdf_begin_stream      pdfbeginstream
#define pdf_buf		      pdfbuf		      
#define pdf_char_map	      pdfcharmap	      
#define pdf_char_used	      pdfcharused	      
#define pdf_create_font_obj      pdfcreatefontobj      
#define pdf_create_obj        zpdfcreateobj      
#define pdf_end_dict          pdfenddict
#define pdf_end_obj         pdfendobj
#define pdf_end_stream      pdfendstream
#define pdf_gone            pdfgone
#define pdf_file		      pdffile		      
#define pdf_flush	      pdfflush	      
#define pdf_font_expand_ratio    pdffontexpandratio    
#define pdf_font_attr	      pdffontattr
#define pdf_font_map	      pdffontmap
#define pdf_font_size	      pdffontsize
#define pdf_last_pdf_box_spec    pdflastpdfboxspec
#define pdf_new_objnum	      pdfnewobjnum
#define pdf_new_dict zpdfnewdict
#define pdf_new_obj zpdfnewobj
#define pdf_ptr		      pdfptr
#define pdf_save_offset       pdfsaveoffset
#define pdf_stream_length       pdfstreamlength



